// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:856468331360:web:187fac3d3b3e8048be5c05',
    messagingSenderId: '856468331360',
    projectId: 'sensor-suhu-kiyah',
    authDomain: 'sensor-suhu-kiyah.firebaseapp.com',
    databaseURL: 'https://sensor-suhu-kiyah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensor-suhu-kiyah.firebasestorage.app',
    measurementId: 'G-QFMCTY3PWN',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:856468331360:android:f73ae85e01533fe8be5c05',
    messagingSenderId: '856468331360',
    projectId: 'sensor-suhu-kiyah',
    databaseURL: 'https://sensor-suhu-kiyah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensor-suhu-kiyah.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:856468331360:ios:e25dde5ffc4da687be5c05',
    messagingSenderId: '856468331360',
    projectId: 'sensor-suhu-kiyah',
    databaseURL: 'https://sensor-suhu-kiyah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensor-suhu-kiyah.firebasestorage.app',
    iosBundleId: 'com.example.sensorSuhuKiyah',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? '',
    appId: '1:856468331360:ios:e25dde5ffc4da687be5c05',
    messagingSenderId: '856468331360',
    projectId: 'sensor-suhu-kiyah',
    databaseURL: 'https://sensor-suhu-kiyah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensor-suhu-kiyah.firebasestorage.app',
    iosBundleId: 'com.example.sensorSuhuKiyah',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:856468331360:web:264e05aff26fc2ffbe5c05',
    messagingSenderId: '856468331360',
    projectId: 'sensor-suhu-kiyah',
    authDomain: 'sensor-suhu-kiyah.firebaseapp.com',
    databaseURL: 'https://sensor-suhu-kiyah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensor-suhu-kiyah.firebasestorage.app',
    measurementId: 'G-M3LWZTP2BL',
  );
}
